llm_provider: openai
model_name: gpt-4o-mini
api_key: ${OPENAI_API_KEY}

active_skills:
  - calculate
  - web_search

channels:
  telegram:
    enabled: false
    token: ${TELEGRAM_BOT_TOKEN}
  whatsapp:
    enabled: false
    token: ${WHATSAPP_TOKEN}

memory:
  enabled: true
  top_k: 5
  path: parmana_memory_db
  embedding_model: sentence-transformers/all-MiniLM-L6-v2
