import json
import asyncio
import sys

# We will build these modules next!
from Core.agent import ParmanaAgent
from Channels.telegram import start_telegram_bot
# from Channels.whatsapp import start_whatsapp_webhook

def load_config():
    """Reads the configuration file generated by install.sh"""
    try:
        with open("config.json", "r") as f:
            return json.load(f)
    except FileNotFoundError:
        print("Error: config.json not found! Please run ./install.sh first.")
        sys.exit(1)

async def main():
    print("Initializing Parmana AI...")
    config = load_config()

    # 1. Initialize the Core Agent (The Brain)
    agent = ParmanaAgent(config)
    print(f"Loaded LLM Provider: {config['llm_provider']} ({config['model_name']})")
    print(f"Active Skills: {', '.join(config['active_skills'])}")

    # 2. Start Enabled Channels (The Ears/Mouth)
    tasks = []

    telegram_config = config["channels"].get("telegram", {})
    if telegram_config.get("enabled"):
        print("Starting Telegram Channel...")
        # We pass the 'agent' to the channel so it knows where to send messages
        tasks.append(start_telegram_bot(telegram_config["token"], agent))

    whatsapp_config = config["channels"].get("whatsapp", {})
    if whatsapp_config.get("enabled"):
        print("Starting WhatsApp Channel... (FastAPI)")
        # tasks.append(start_whatsapp_webhook(whatsapp_config["token"], agent))

    if not tasks:
        print("No channels enabled! Parmana has no way to communicate.")
        print("Please enable a channel in config.json.")
        sys.exit(0)

    # Run all enabled channels concurrently
    await asyncio.gather(*tasks)

if __name__ == "__main__":
    # Windows fix for asyncio
    if sys.platform.startswith("win"):
        asyncio.set_event_loop_policy(asyncio.WindowsSelectorEventLoopPolicy())
    
    try:
        asyncio.run(main())
    except KeyboardInterrupt:
        print("\nParmana AI shutting down...")
